Python3/Roman_to_Integer.py

#hacktoberfest #hacktoberfest-accepted #contribute #open-source #hacktoberfest2022 #leetcodesolution

Initial Commit

---

CPP/word_break.cpp

Hey @avijitsen7076 sir, i added code for  Word Break problem in CPP.
Can you review and merge it?

Added Word Break(DP) problem in CPP

---

cpp pattren-2

cpp pattren 2

---

Leetcode58_LengthOfLastWord.cpp
Leetcode67_AddBinary.cpp

added leetocde 58 problem solution

---

Leetcode1791_FindCenterOfStarGraph.cpp

Added Leetcode 1791 problem solution.

added leetcode 1791 problem solution

---

Leetcode29_DivideTwoIntegers.cpp

Added leetcode 29 easy problem solution.

added leetcode 29 problem solution

---

Leetcode1971_FindIfPathExistInGraph.cpp

Added leetcode 1971 problem DFS solution

added leetcode 1971 problem solution

---

cpp pattern-3

cpp pattern-3

---

CPP/kadane-algo.txt

updated with kadanes algorithm

kadanes algorithm

---

CPP/Add_Two_Numbers.cpp

Add Two Numbers

---

CPP/Fractional_Knapsack.cpp

GFG fractional knapsack solution. Please merge the PR.

Fractional Knapsack

---

CPP/Job_Sequencing_Problem.cpp

solution for GFG Job Sequencing Problem. Please merge.

Job Sequencing Problem

---

CPP/binary_tree_zigzag_level_order_traversal.cpp

@avijitsen7076 Accept my PR under Hacktoberfest

Binary Tree Zigzag Level Order Traversal

---

CPP/Infix_To_Postfix.cpp

Added C++ code for infix to postfix.

---

CPP/BFS_of_graph.cpp

Solution of GFG BFS of graph problem. Pls merge.

BFS of graph

---

CPP/dijkstra's.cpp

I have added Dijkstra's algorithm (C++) in cpp folder. Please accept my PR under hacktoberfest.

Dijkstra's Algorithm in C++

---

CPP/Lowest Common Ancestor of a Binary Tree.cpp

@avijitsen7076 Accept my PR under Hacktoberfest

Lowest Common Ancestor of a Binary Tree

---

CPP/Maximum_Width_of_Tree.cpp

Solution of GFG Maximum Width of Tree problem

Maximum Width of Tree

---

CPP/gcd_recursive.cpp

Recursive cpp code for gcd added.

---

CPP/FindArrayReverse.cpp

 FindArrayReverse.cpp

---

Python3/Count_digits.py

Please let me know if anything else is required, dont mark it spam or anything please.

Short trick to count digits
